name: deploy

# 代码提交到main分支时触发github action
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true
                  # 这里最好与本机hugo版本一致，例如：hugo-version: "0.121.2"
                  # 有时github部署会自动更新hugo版本导致部署失败
                  # extended来控制是否为扩展版本

            - name: Build Web
              run: hugo

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  external_repository: AnthonyBvvd/AnthonyBvvd.github.io
                  publish_branch: main
                  publish_dir: ./public
                  commit_message: ${{ github.event.head_commit.message }}
